version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7.1-fpm-alpine
        volumes:
            - .:/usr/share/nginx/html

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=web
            - MYSQL_USER=web
            - MYSQL_PASSWORD=pass
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql

    redis:
        image: redis:3.2-alpine
        ports:
            - 6379:6379
        volumes:
            - ./docker/volumes/redis:/var/lib/redis

    memcached:
        image: memcached:1.4-alpine
        ports:
            - 11211:11211
